#!/bin/bash

# Maintainer : G0urav <https://github.com/heapbytes>
# Developed by Team Vitunix

fix_lsb_release() {
    local file=/etc/lsb-release

    if [[ -z "`grep "^DISTRIB_RELEASE=" $file`" ]] ; then
        # add missing DISTRIB_RELEASE=
        echo "DISTRIB_RELEASE=rolling" >> "$file"
    fi
    sed -i "$file" \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=Vitunix|' \
        -e 's|^DISTRIB_RELEASE=.*$|DISTRIB_RELEASE=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Vitunix\"|'
}

fix_os_release() {
    local file=/usr/lib/os-release

    sed -i "$file" \
        -e 's|^NAME=.*$|NAME=\"Vitunix\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Vitunix\"|' \
        -e 's|^ID=.*$|ID=Vitunix|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^BUILD_ID=.*$|BUILD_ID=rolling|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://vitunix.github.io/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://vitunix.github.io/wiki\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://github.com/vitunix/vitunix-iso"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/vitunix/vitunix-iso/issues"|' \
        -e 's|^LOGO=.*$|LOGO=Vitunix|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

	# fix issue file
    sed -i 's|Arch Linux|Vitunix|g' /etc/issue /usr/share/factory/etc/issue
}

main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  fix_os_release ;;
        lsb-release) fix_lsb_release ;;
        "")          fix_os_release
                     fix_lsb_release
                     ;;
    esac
}

main "$@"
